name: Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    - name: Compile requirements
      run: pip-compile 6.419x/requirements.in
    - name: Install dependencies
      run: pip install -r 6.419x/requirements.txt
    - name: Run tests
      run: |
        for file in $(find . -name '*_test.py'); do
          python $file
        done